name: Build dasher.cpp

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-raylib

    - name: Compile dasher.cpp
      run: |
        g++ -o dasher.exe dasher.cpp -lraylib -lopengl32 -lgdi32 -lwinmm

    - name: Upload dasher.exe
      uses: actions/upload-artifact@v2
      with:
        name: dasher-exe
        path: dasher.exe
