name: Build and Deploy to Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh

    - name: Build with Emscripten
      run: |
        source ./emsdk/emsdk_env.sh
        emcc -o index.html main.cpp -s USE_GLFW=3 -s USE_WEBGL2=1 -s WASM=1 --shell-file shell_minimal.html

    - name: Move build to folder
      run: |
        mkdir -p build
        mv index.html build/

    - name: Commit and Push build folder
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add build/
        git commit -m "Add build artifacts"
        git push origin main
